name: angel_twig_dart
version: 2.0.0
description: Angel support for the Jael templating engine, similar to Blade or Liquid.
author: Isaque Neeves <insinfo2008@gmail.com>
homepage: https://github.com/angel-dart/jael/tree/master/jael
environment:
  sdk: ">=2.0.0-dev <=3.0.0"
dependencies:
  angel_framework: ^2.0.0-alpha
  code_buffer: ^1.0.0
  file: ^5.0.0
  jael: ^2.0.0
  twig_dart_preprocessor: #^2.0.0
    path: ../twig_dart_preprocessor
  symbol_table: ^2.0.0
dev_dependencies:
  angel_test: ^2.0.0-alpha
  html:
  test: ^1.0.0
