builders:
  twig_web:
    import: "package:twig_web/builder.dart"
    builder_factories:
      - twigComponentBuilder
    build_extensions:
      .dart:
        - .twig_web_cmp.g.part
    auto_apply: root_package
    applies_builders: ["source_gen|combining_builder", "source_gen|part_cleanup"]