name: twig_dart_web
version: 3.0.0
description: Experimental virtual DOM/SPA engine built on twig_dart_web. Supports SSR.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/twig_dart

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  build: ^2.0.1 #Null safety
  build_config: ^1.0.0 #Null safety
  code_builder: ^4.0.0 #Null safety
  twig_dart: ^3.0.0 #Null safety
  twig_dart_preprocessor: ^3.0.1 #Null safety
  source_gen: ^1.0.0 #Null safety
  file: ^6.1.0 #Null safety
  path: ^1.8.0 #Null safety
  analyzer: ^1.5.0 #Null safety
  
dev_dependencies:
  build_runner: ^2.0.2  #Null safety
  build_web_compilers: ^3.0.0 #Null safety
  pedantic: ^1.11.0 #Null safety