name: twig_dart_language_server
version: 3.0.0
description: Language Server Protocol implementation for the Twig templating engine.
author: Isaque Neves <insinfo2008@gmail.com>
homepage: https://github.com/insinfo/twig_dart

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  args: ^2.1.0 #Null safety
  #dart_language_server: ^0.1.16 #0.1.14 #^0.1.3
  galileo_dart_language_server: ^3.0.1
  file: ^6.1.0 #Null safety
  io: ^1.0.0 #Null safety
  twig_dart: ^3.0.0 #Null safety
  twig_dart_preprocessor: ^3.0.1 #Null safety
  json_rpc_2: ^3.0.1 #Null safety
  logging: ^1.0.1 #Null safety
  path: ^1.8.0 #Null safety
  source_span: ^1.8.1 #Null safety
  string_scanner: ^1.1.0 #Null safety
  essential_symbol_table: ^2.0.1 #Null safety
executables:
  twig_dart_language_server: twig_dart_language_server